events {}

http {
    server {
        listen 80;

        # USER SERVICE
        location /users {
            proxy_pass http://user_service:5002;
        }

        # AUTH SERVICE
        location /auth/ {
            proxy_pass http://auth_service:5001/;
        }

        # DRIVER SERVICE
        location /drivers/ {
            proxy_pass http://driver_service:5005/;
        }
        #ORDER SERVICE
        location /orders {
            proxy_pass http://order_service:5003;
        }
        
        #payment SERVICE
        location /payment {
            proxy_pass http://payment_service:5004;
        }
    }
}